version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ../db:/var/lib/postgresql/data
    env_file:
      - ../db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ../appdata:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
    env_file:
      - ../db.env
    depends_on:
      - db
      - redis

  web:
    build: ./web
    restart: always
    volumes:
      - ../appdata:/var/www/html:ro
    env_file:
      - ssl.env
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ../appdata:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

###### self signed
  # omgwtfssl:
  #   image: paulczar/omgwtfssl
  #   restart: "no"
  #   volumes:
  #     - ./certs:/certs
  #   environment:
  #     - SSL_SUBJECT=cloud.traume.com.br
  #     - CA_SUBJECT=cloud@traume.com.br
  #     - SSL_KEY=/certs/cloud.traume.com.br.key
  #     - SSL_CSR=/certs/cloud.traume.com.br.csr
  #     - SSL_CERT=/certs/cloud.traume.com.br.crt
  #   networks:
  #     - proxy-tier


networks:
  proxy-tier:
